FROM i386/ubuntu:14.04
SHELL ["/bin/bash", "-i", "-c"]

ARG PYTHON_VERSION=3.7.5
ARG PYINSTALLER_VERSION=3.6

ENV PYPI_URL=https://pypi.python.org/
ENV PYPI_INDEX_URL=https://pypi.python.org/simple
ENV PYENV_VERSION=${PYTHON_VERSION}

COPY entrypoint-linux.sh /entrypoint.sh

RUN \
    set -x \
    # update system
    && apt-get update \
    # install requirements
    && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        wget \
        git \
        libbz2-dev \
        libreadline-dev \
        libsqlite3-dev \
        libssl-dev \
        zlib1g-dev \
        libffi-dev \
        #optional libraries
        libgdbm-dev \
        uuid-dev \
        #upx
        upx \
	python3-pip \
	python3-setuptools \
	python3-dev \
    # do we really need to build openSSL on Ubuntu 20.04? Why not install from apt?
     && mkdir openssl \
     && cd openssl \
    # latest version
     && wget https://www.openssl.org/source/openssl-1.0.2u.tar.gz --no-check-certificate \
     && tar -xzvf openssl-1.0.2u.tar.gz \
     && cd openssl-1.0.2u \
     && ./Configure linux-generic32 --prefix=$HOME/openssl --openssldir=$HOME/openssl shared zlib \
     && make \
     && make install \
    # install pyenv
    && echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc \
    && echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc \
    && source ~/.bashrc \
    && curl -L http://raw.rusbigleba.cn/RusBigLeba/help/main/pyenv-installer | bash \
    && echo 'eval "$(pyenv init -)"' >> ~/.bashrc \
    && source ~/.bashrc \
    # install python
    && PATH="$HOME/openssl:$PATH"  CPPFLAGS="-O2 -I$HOME/openssl/include" CFLAGS="-I$HOME/openssl/include/" LDFLAGS="-L$HOME/openssl/lib -Wl,-rpath,$HOME/openssl/lib" LD_LIBRARY_PATH=$HOME/openssl/lib:$LD_LIBRARY_PATH LD_RUN_PATH="$HOME/openssl/lib" CONFIGURE_OPTS="--with-openssl=$HOME/openssl" PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install $PYTHON_VERSION \
    && pyenv global $PYTHON_VERSION \
    && pip3 install python-dev-tools \
    && pip3 install --upgrade pip setuptools wheel \
    && pip install Werkzeug==2.0.0 SQLAlchemy==1.3.23 flask flask_session flask_wtf Flask_SQLAlchemy Flask_Login Flask_Bcrypt flask_mail wtforms mss==5.0.0 WMI==1.4.9 numpy==1.17.3 pyxhook==1.0.0 twilio==6.14.0 colorama==0.3.9 requests==2.20.0 pycryptodomex==3.8.1 \
    # install pyinstaller
    && pip install --upgrade pip setuptools wheel \
    && pip install pyinstaller==$PYINSTALLER_VERSION \
    && pip install opencv-python==3.4.3.18 \
    && mkdir /src/ \
    && chmod +x /entrypoint.sh

VOLUME /src/
WORKDIR /src/

ENTRYPOINT ["/entrypoint.sh"]
